name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry Run'
        type: boolean
        default: true

  workflow_call:
    secrets:
      PUBLISH_NPM:
        required: true

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup
        uses: ./.github/actions/setup

      - run: |
          pnpm i
          pnpm build

      # Release Please has already incremented versions and published tags, so we just
      # need to publish all unpublished versions to NPM here
      # See: https://github.com/lerna/lerna/tree/main/commands/publish#bump-from-package
      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLISH_NPM}}
        run: pnpm publish packages/perf-insight ${{ (inputs.dry_run && '--dry-run') || '' }}
